### ISSUE TITLE
.MCD as input file format

### ISSUE THREAD

**Issue by algebio** [CellProfiler/tutorials#32]
Hi

I have to analyse .mcd files exported from a Hyperion analyser. I normally use imctools to transform it into tif files. I was wondering if this is the only way to use my .mcd files in CellProfiler or there other ways to directly use them as input.

Regards
Juan

**Comment by bethac07** [comment]
Hi Juan,

If you can open it in Fiji, then in theory you can open it in CellProfiler (though you may need the newest version, we added support for a bunch of formats in our latest release). 

If you don't have success, I would ask you to make a new thread in image.sc and upload an image so we can give it a try; if you don't mind, I'll close this issue here, since it's not a question specifically about a tutorial.

Thanks for reaching out!

**Comment by algebio** [comment]
Thanks Beth
